CREATE TABLE roles (
	ID SERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL
);

CREATE TABLE locations (
	ID SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE status (
	ID SERIAL PRIMARY KEY,
	name VARCHAR(20) NOT NULL
);

CREATE TABLE users (
	ID SERIAL PRIMARY KEY,
	role INT REFERENCES roles(ID),
	location INT REFERENCES locations(ID),
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE vendors (
	ID SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	phone VARCHAR(255)
);

CREATE TABLE items (
	ID SERIAL PRIMARY KEY,
	location INT REFERENCES locations(ID),
	status INT REFERENCES status(ID),
	vendor INT REFERENCES vendors(ID),
	name VARCHAR(255) NOT NULL,
	quantity INT NOT NULL
);